version: "3.8"

services:
  app:
    build:
      context: ./packages/api
      dockerfile: Dockerfile.mac
    container_name: flask_app
    ports:
      - "5001:5001"
    environment:
      - VLLM_URL=${VLLM_URL}
      - SQLITE_PATH=/app/data/resume_matcher.db
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - resume_matcher_sqlite:/app/data
    networks:
      - app-network

  frontend:
    build:
      context: ./packages/web
      dockerfile: Dockerfile.dev
    container_name: vue_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5001
    volumes:
      - ./packages/web:/app
      - /app/node_modules
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  resume_matcher_sqlite:
